# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hall Design
collections:
  - feedbacks
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
languages: ["ua", "en"]
exclude_from_localizations: ["js", "image", "font", "css"]
# Build settings
theme: minima
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "image/projects"
    values:
      image: true
  - scope:
      path: "image/partners"
    values:
      partners: true
  - scope:
      path: "image/we_work"
    values:
      we_work: true
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
image_optim:
  image_glob: "image/**/*.{gif,jpg,jpeg,png}"
email: hall.designes@gmail.com
ua_phone_number: +38(098)62-84-391
eu_phone_number: ""
behance: https://www.behance.net/halldesign
instagram: https://www.instagram.com/hall.design/
pinterest: https://pinterest.com/halldesign_ua/
years_of_expirience: 5
projects_completed: 185
designers:
  ua:
    - role: Керівник студії Hall Design, головний дизайнер, створюю інтерʼєри з 2017 року
      name: Крістіна
      image: /image/team/kris.jpg
      behance: https://www.behance.net/kristingalykin
    - role: Дизайнер інтерʼєру, візуалізатор, проєктувальник, досвід роботи - з 2021 року
      name: Людмила
      image: /image/team/liuda.jpg
      behance: https://www.behance.net/lyudmikulesha
    - role: Дизайнер інтерʼєру, візуалізатор, досвід роботи - з 2022 року
      name: Олег
      image: /image/team/oleg.jpg
      behance: https://www.behance.net/olehhumennyi
  en:
    - role: Дизайнер
      name: Крістіна
      image: /image/team/kris.jpg
      behance: https://www.behance.net/kristingalykin
    - role: Дизайнер
      name: Людмила
      image: /image/team/liuda.jpg
      behance: https://www.behance.net/lyudmikulesha
    - role: Дизайнер
      name: Олег
      image: /image/team/oleg.jpg
      behance: https://www.behance.net/olehhumennyi
